language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose up --build && docker-compose run stamper-api sh -c "python manage.py test"
