language: python
python:
  - "3.9"

services:
  - docker

before_script: 
  - pip install docker-compose
  - docker-compose up -d --build

script:
  - docker-compose exec stamper-api python manage.py test --settings=config.settings.testing

after_script:
  - docker-compose down
