version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: stamper
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.env
    ports:
      - "8000:8000"
    command: /start
    networks:
      - backend

  postgres:
    image: postgres:13.0
    restart: always
    hostname: stamper-db
    container_name: stamper-db
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=cms,postgres
    networks:
      - backend

networks:
  backend:

volumes:
  local_postgres_data: {}
