[tool.poetry]
name = "uml"
version = "0.1.0"
description = ""
authors = ["BonaSoft"]

[tool.poetry.dependencies]
python = "3.9"
django = "3.1"
django-environ = "0.4.5"
djangorestframework = "3.12.1"
django-model-utils = "4.0.0"
django_extensions = "3.0.9"
Werkzeug = "1.0.1"
psycopg2 = "2.8.6"
